### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by BryantGao** [MCG-NJU/SportsMOT#1]
When I submit my results.zip file, I met the error as:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpmcsGgt/run/program/evaluate_half_test.py", line 22, in 
    organize_input_half.process(input_dir)
  File "/tmp/codalab/tmpmcsGgt/run/program/organize_input_half.py", line 47, in process
    "Uploaded results are not one-to-one matches to the test set.")
Exception: Uploaded results are not one-to-one matches to the test set.
And all test set file were contained in it
![image](https://user-images.githubusercontent.com/40635230/171316076-ec77af41-89b0-4488-8508-35e1c33899f4.png)

**Comment by ZXYFrank** [comment]
Thanks for your feed back! Please refer to the [forum on Codalab](https://codalab.lisn.upsaclay.fr/forums/4433/) for details.
