### ISSUE TITLE
是否设置屏蔽区？

### ISSUE THREAD

**Issue by goldentimecoolk** [MCG-NJU/SportsMOT#13]
非常棒的工作！
请问这个数据集是否设置了屏蔽区去忽略观众、替补等无关人员？不屏蔽的话对最终的性能影响还蛮大。
谢谢。

**Comment by yutaocui** [comment]
你好，我们的数据并没有可以去设置屏蔽区，我们认为算法应该具备能力也能够较好地做到识别场上球员和观众～

**Comment by goldentimecoolk** [comment]
@yutaocui 感谢回复。也就是说只标注了场上球员，在训练模型、比如检测器的时候，告诉模型标注了的场上球员为正样本，观众或替补由于没有标注就和其他背景一样为记为负样本。

**Comment by yutaocui** [comment]
> @yutaocui 感谢回复。也就是说只标注了场上球员，在训练模型、比如检测器的时候，告诉模型标注了的场上球员为正样本，观众或替补由于没有标注就和其他背景一样为记为负样本。

是这样的

**Comment by goldentimecoolk** [comment]
明白啦，谢谢！
