### ISSUE TITLE
Do you have plans to set SportsMOT as a benchmark?

### ISSUE THREAD

**Issue by xiaocc612** [MCG-NJU/SportsMOT#3]
Hi,
  As the title says，do you have plans to set SportsMOT as a benchmark? Also, can you open the interface again to evaluate the results of the test set? And give the official evaluation results of some modern trackers like CenterTrack, ByteTrack, etc. Thanks for your contribution to the community.

**Comment by yutaocui** [comment]
Yes, we have benchmarked some prevailing trackers (e.g., ByteTrack, OcSORT, CenterTrack, FairMOT, GTR, QDTrack, TransTrack and our proposed one) on SportsMOT. The official evaluation tools and code will be made public soon. Thanks for your attention.

**Comment by xiaocc612** [comment]
> Yes, we have benchmarked some prevailing trackers (e.g., ByteTrack, OcSORT, CenterTrack, FairMOT, GTR, QDTrack, TransTrack and our proposed one) on SportsMOT. The official evaluation tools and code will be made public soon. Thanks for your attention.
How much longer before the benchmark is released? And can you open the Coalab review portal again in the near future? I am very anxious to evaluate our algorithm on your dataset.

**Comment by xiaocc612** [comment]
> Yes, we have benchmarked some prevailing trackers (e.g., ByteTrack, OcSORT, CenterTrack, FairMOT, GTR, QDTrack, TransTrack and our proposed one) on SportsMOT. The official evaluation tools and code will be made public soon. Thanks for your attention.

How much longer before the benchmark is released? And can you open the Coalab review portal again in the near future? I am very anxious to evaluate our algorithm on your dataset.

**Comment by felipearrudamoura** [comment]
Hello! I would like to test in some football data collection for sports performance research. Do you have plans to share the code/colab?
