### ISSUE TITLE
Can't download the dataset 

### ISSUE THREAD

**Issue by Mu-Magdy** [MCG-NJU/SportsMOT#6]
I can't find the link to download the dataset on Codalab competition participate/get data

**Comment by yutaocui** [comment]
Thanks for your attention. The download link of training and validation datasets is as follows (typically, you should sign in to see the download link):
[onedrive](https://onedrive.live.com/?authkey=%21AOa4CTBaGd05zjU&id=91819DD8AE2EDED8%21131&cid=91819DD8AE2EDED8&parId=root&parQt=sharedby&o=OneUp) md5 checksum: 3e8c5c540375e71e70b411422b419e03
[baidu drive](https://pan.baidu.com/share/init?surl=wryLDorjOscBmDMrU3RThA) password: ambs
